print("Ingresa 3 numeros: \n")
num1 = int(input(""))
num2 = int(input(""))
num3 = int(input(""))
maxnum = max(num1,num2,num3)
minnum = min(num1,num2,num3)
print("El numero más grande es: {},\nEl numero más pequeño es: {}".format(maxnum,minnum))
